on:
  push:
    tags:
      - "v*"

name: Create Release
run-name: Create Release

jobs:
  Build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:  
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build Output  
  Create-Release:
      - name: Create Release
        uses: softprops/actin-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          draft: true
          prerelease: false
